import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pl' | 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pl: {
    // Header
    'company.name': 'FoxP2',
    'nav.web2': 'Web2',
    'nav.web3': 'Web3',
    'nav.contact': 'Kontakt',
    'theme.toggle': 'Przełącz motyw',
    'language.select': 'Wybierz język',
    'auth.login': 'Zaloguj się',
    'auth.logout': 'Wyloguj się',
    
    // Homepage - Animated Slogan
    'hero.animated.tworzymy': 'Tworzymy',
    'hero.animated.z': 'z',
    'hero.animated.pasja': 'pasją!',
    'hero.title': 'Tworzymy z pasją!',
    'hero.subtitle': 'Jesteśmy firmą specjalizującą się w nowoczesnych rozwiązaniach funkcjonujących zarówno w obszarze Web2 jak i Web3. Testujemy możliwości bezpiecznego zarządzania danymi w zdecentralizowanym środowisku blockchain\'owym.',
    'web2.title': 'Web2',
    'web2.description': 'Tradycyjne aplikacje webowe, systemy zarządzania treścią, e-commerce i rozwiązania korporacyjne',
    'web3.title': 'Web3',
    'web3.description': 'Zdecentralizowane aplikacje, blockchain, smart kontrakty i technologie przyszłości',
    'contact.button': 'Skontaktuj się z nami',
    
    // Projects sections
    'projects.web2.title': 'Nasze projekty Web2',
    'projects.web2.subtitle': 'Naszym wiodącym projektem Web2 jest platforma wspierająca podmioty organizujące żywienie zbiorowe o nazwie',
    'projects.web2.subtitle2': 'KaSKa - Kapitalny System Kateringowy',
    'projects.web2.additional': 'System KaSKa składa się z następujących trzech zasadniczych elementów:',
    'projects.web2.moreInfo': 'Więcej informacji',
    'projects.web2.project1.title': 'KaSKa Administracja',
    'projects.web2.project1.description': 'Aplikacja do administrowania systemem z funkcjami:\n- dodawania i edycji warunków żywienia w określonej lokalizacji,\n- zarządzania kontami użytkowników (Rodziców, Opiekunów i Dzieci, Osób Żywionych),\n- generowania raportów, wykazów i list żywionych\n- oraz planowania żywienia.\nIntegralną częścią aplikacji jest moduł kompozytora menu z funkcjami planowania żywienia z gotowej bazy danych dań i składników.\nModuł finansowy pozwala kontrolować ewidencję opłat za zamówione posiłki i bilanse rezygnacji.',
    'projects.web2.project2.title': 'KaSKa Panel Rodzica',
    'projects.web2.project2.description': 'KaSKa Panel Rodzica to platforma sprzedażowa posiłków z integracją płatności i systemem zarządzania posiłkami. Aplikacja pracuje zarówno w komputerze jak i urządzeniach mobilnych (tablet, smartfon). Posiada następujące cechy funkcjonalne:\n- intuicyjne zakładanie kont Rodzica jak i Dziecka/Dzieci z niezbędną, minimalną ilością wprowadzanych danych osobowych,\n- planowanie posiłków w poszczególnych dniach żywieniowych,\n- możliwość dokupienia posiłków w dniach oznaczonych jako \'bez posiłku\',\n- możliwość rezygnacji z wybranego posiłku jak i anulowania tej rezygnacji,\n- funkcja koszyka i bilansu rezygnacji,\n- aktywne wsparcie zespoły wsparcia IT.\nZawiera moduł ogłoszeń z aktualnymi wiadomościami od organizatora żywienia.',
    'projects.web2.project3.title': 'KaSKa PikPik',
    'projects.web2.project3.description': 'PikPik to terminal stołówkowo-kuchenny, który instalujemy przy okienku wydawki w szkolnej stołówce. Każde zarejestrowane w systemie Dziecko otrzymuje Cyfrową Kartę Obiadową, z pomocą której będzie mogło \'odbić się\' w PikPik\'u. PikPik wita się z Dzieckiem, a po odbiciu karty na ekranie pojawi się zaproszenie do spożycia wybranego na ten dzień przez Rodzica posiłku. W tym samym czasie na ekranie monitora w kuchni obsługa będzie miała wgląd w kolejkę po posiłek, ilości zaplanowanych, wydanych i pozostałych do wydania posiłków, a także o dietach, które należy uwzględnić w bieżącym dniu dla wybranych Dzieci. Na koniec dnia PikPik wyśle raport o przebiegu dnia żywieniowego oraz automatycznie wyłączy się. Następnego dnia, także automatycznie, włączy się o określonej godzinie i samodzielnie wygeneruje listę żywionych w tym dniu Dzieci. A wszystko to bez dodatkowych kosztów!',
    
    'projects.web3.title': 'Co robimy w Web3?',
    'projects.web3.subtitle': 'Wdrażamy pionierskie rozwiązania w **technologii blockchain** i **zdecentralizowanych bazach danych**.',
    'projects.web3.intro': 'Przygotowaliśmy następujące projekty Web3:',
    'projects.web3.project1.title': 'DeFi Protocol',
    'projects.web3.project1.description': 'Protokół zdecentralizowanych finansów z możliwością stakingu i yield farmingu.',
    'projects.web3.project2.title': 'NFT Marketplace',
    'projects.web3.project2.description': 'Platforma handlu tokenami NFT z niskimi opłatami transakcyjnymi.',
    'projects.web3.project3.title': 'DAO Governance',
    'projects.web3.project3.description': 'System zarządzania zdecentralizowaną organizacją autonomiczną.',
    
    // Cooperation process
    'cooperation.title': 'Proces współpracy',
    'cooperation.subtitle': 'Cztery etapy realizacji Twojego projektu',
    'cooperation.stage1.title': '1. Analiza potrzeb',
    'cooperation.stage1.description': 'Szczegółowa analiza wymagań i określenie zakresu projektu.',
    'cooperation.stage2.title': '2. Projektowanie',
    'cooperation.stage2.description': 'Tworzenie architektury systemu i projektów interfejsu użytkownika.',
    'cooperation.stage3.title': '3. Implementacja',
    'cooperation.stage3.description': 'Rozwój aplikacji z regularnymi aktualizacjami postępu.',
    'cooperation.stage4.title': '4. Wdrożenie',
    'cooperation.stage4.description': 'Uruchomienie systemu i wsparcie techniczne po wdrożeniu.',
    
    // Contact Form
    'contact.title': 'Skontaktuj się z nami',
    'contact.firstName': 'Imię',
    'contact.lastName': 'Nazwisko',
    'contact.email': 'Adres email',
    'contact.phone': 'Numer telefonu (opcjonalnie)',
    'contact.message': 'Wiadomość',
    'contact.submit': 'Wyślij wiadomość',
    'contact.cancel': 'Anuluj',
    'contact.success': 'Wiadomość została wysłana pomyślnie!',
    'contact.error': 'Wystąpił błąd podczas wysyłania wiadomości.',
    'contact.messageLimit': 'Maksymalnie 250 znaków',
    'contact.requiredFields': 'Wszystkie wymagane pola muszą być wypełnione',
    'contact.sending': 'Wysyłanie...',
    'contact.privacyNotice': 'Wprowadzone tutaj dane będą przechowywane w sposób zdecentralizowany (w blockchain). Nie będą gromadzona na tradycyjnym serwerze. Będą widoczne tylko dla Administratora tej strony.',
    
    // Footer
    'footer.copyright': '© 2025. Stworzone przez FoxP2 z',
    'footer.copyrightSuffix': 'przy użyciu',
    'footer.copyrightText': '© 2025. Z ❤ przez FoxP2',
    'footer.love': '❤️',
    'footer.contact.title': 'Kontakt',
    'footer.contact.openchat': 'Kontakt poprzez OpenChat',
    'footer.contact.phone': '+48 503 074 672',
    'footer.contact.email': 'biuro@foxp2.pl',
    'footer.services.title': 'Usługi',
    'footer.services.web2': 'Rozwiązania Web2',
    'footer.services.web3': 'Technologie Web3',
    'footer.services.consulting': 'Konsulting IT',
    'footer.principalId.label': 'Twój PrincipalID',
    'footer.principalId.admin': 'konto Administratora',
    'footer.principalId.copy': 'Kopiuj do schowka',
    'footer.principalId.copied': 'Skopiowano!',

    // RODO
    'rodo.button': 'RODO',
    'rodo.title': 'Informacja o przetwarzaniu danych osobowych',
    'rodo.purpose.title': 'Cel przetwarzania danych',
    'rodo.purpose.content': 'Dane osobowe podane w formularzu kontaktowym są przetwarzane w celu udzielenia odpowiedzi na Państwa zapytanie oraz nawiązania kontaktu w sprawach związanych z działalnością firmy FoxP2.',
    'rodo.scope.title': 'Zakres przetwarzanych danych',
    'rodo.scope.firstName': 'Imię',
    'rodo.scope.lastName': 'Nazwisko',
    'rodo.scope.email': 'Adres e-mail',
    'rodo.scope.phone': 'Numer telefonu (opcjonalnie)',
    'rodo.scope.message': 'Treść wiadomości',
    'rodo.storage.title': 'Sposób przechowywania danych',
    'rodo.storage.content': 'Dane są przechowywane w sposób zdecentralizowany w technologii blockchain Internet Computer. Nie są gromadzone na tradycyjnych serwerach, co zapewnia wysokie bezpieczeństwo i odporność na awarie.',
    'rodo.access.title': 'Dostęp do danych',
    'rodo.access.content': 'Dostęp do przesłanych danych ma wyłącznie Administrator strony internetowej firmy FoxP2. Dane nie są udostępniane osobom trzecim bez zgody osoby, której dane dotyczą.',
    'rodo.rights.title': 'Prawa osób, których dane dotyczą',
    'rodo.rights.access': 'Prawo dostępu do swoich danych osobowych',
    'rodo.rights.rectification': 'Prawo do sprostowania nieprawidłowych danych',
    'rodo.rights.erasure': 'Prawo do usunięcia danych (prawo do bycia zapomnianym)',
    'rodo.rights.portability': 'Prawo do przenoszenia danych',
    'rodo.rights.objection': 'Prawo do wniesienia sprzeciwu wobec przetwarzania',
    'rodo.contact.title': 'Kontakt w sprawach ochrony danych',
    'rodo.contact.content': 'W sprawach związanych z ochroną danych osobowych można kontaktować się pod adresem e-mail: biuro@foxp2.pl lub telefonicznie: +48 503 074 672.',

    // Admin Messages
    'admin.messages.title': 'Wiadomości',
    'admin.messages.dialogTitle': 'Wiadomości kontaktowe',
    'admin.messages.noMessages': 'Brak wiadomości kontaktowych',
    'admin.messages.deleteSuccess': 'Wiadomość została usunięta',
    'admin.messages.deleteError': 'Błąd podczas usuwania wiadomości',
    'admin.messages.selectAll': 'Zaznacz wszystkie',
    'admin.messages.export.button': 'Eksportuj do PDF',
    'admin.messages.export.title': 'Wiadomości kontaktowe',
    'admin.messages.export.generated': 'Wygenerowano',
    'admin.messages.export.totalMessages': 'Łączna liczba wiadomości',
    'admin.messages.export.selectedMessages': 'Wybrane wiadomości',
    'admin.messages.export.name': 'Imię i nazwisko',
    'admin.messages.export.email': 'Email',
    'admin.messages.export.phone': 'Telefon',
    'admin.messages.export.date': 'Data',
    'admin.messages.export.message': 'Wiadomość',
    'admin.messages.export.footer': 'Wiadomości kontaktowe wygenerowane automatycznie',
    'admin.messages.export.success': 'PDF został wygenerowany pomyślnie',
    'admin.messages.export.error': 'Błąd podczas generowania PDF',
    'admin.messages.export.noSelection': 'Wybierz co najmniej jedną wiadomość do eksportu',

    // Scroll to top
    'scrollToTop.label': 'Przewiń do góry',

    // Web3 Admin
    'web3.admin.title': 'Zarządzanie kartami Web3',
    'web3.admin.manage': 'Zarządzaj',
    'web3.admin.add': 'Dodaj kartę',
    'web3.admin.edit': 'Edytuj kartę',
    'web3.admin.description': 'Dodaj lub edytuj karty w sekcji Web3',
    'web3.admin.noCards': 'Brak kart Web3. Dodaj pierwszą kartę.',
    'web3.admin.form.title': 'Tytuł',
    'web3.admin.form.titlePlaceholder': 'Wprowadź tytuł karty',
    'web3.admin.form.icon': 'Ikona',
    'web3.admin.form.description': 'Opis',
    'web3.admin.form.descriptionPlaceholder': 'Wprowadź opis karty',
    'web3.admin.form.buttonTitle': 'Tekst przycisku',
    'web3.admin.form.buttonTitlePlaceholder': 'np. Dowiedz się więcej',
    'web3.admin.form.link': 'Link',
    'web3.admin.form.linkPlaceholder': 'https://example.com',
    'web3.admin.validation.required': 'Wszystkie pola są wymagane',
    'web3.admin.success.added': 'Karta została dodana pomyślnie',
    'web3.admin.success.updated': 'Karta została zaktualizowana pomyślnie',
    'web3.admin.success.deleted': 'Karta została usunięta pomyślnie',
    'web3.admin.error.add': 'Błąd podczas dodawania karty',
    'web3.admin.error.update': 'Błąd podczas aktualizacji karty',
    'web3.admin.error.delete': 'Błąd podczas usuwania karty',
    'web3.admin.confirm.delete': 'Czy na pewno chcesz usunąć tę kartę?',
    'web3.admin.autoTranslation': 'Automatyczne tłumaczenie na angielski i niemiecki',
    'web3.admin.form.tab': 'Formularz',
    'web3.admin.preview.tab': 'Podgląd tłumaczeń',
    'web3.admin.generatePreview': 'Wygeneruj podgląd tłumaczeń',
    'web3.admin.preview.polish': 'Polski (oryginał)',
    'web3.admin.preview.english': 'English (auto)',
    'web3.admin.preview.german': 'Deutsch (auto)',
    'web3.admin.preview.note': 'Tłumaczenia są generowane automatycznie. Karta zostanie zapisana w języku polskim, a tłumaczenia będą wyświetlane dynamicznie w zależności od wybranego języka.',
    'web3.admin.preview.instruction': 'Wypełnij formularz i kliknij "Wygeneruj podgląd tłumaczeń" aby zobaczyć automatyczne tłumaczenia.',

    // Common
    'common.loading': 'Ładowanie...',
    'common.save': 'Zapisz',
    'common.saving': 'Zapisywanie...',
    'common.cancel': 'Anuluj',
    'common.edit': 'Edytuj',
    'common.delete': 'Usuń',
    'common.close': 'Zamknij',
  },
  en: {
    // Header
    'company.name': 'FoxP2',
    'nav.web2': 'Web2',
    'nav.web3': 'Web3',
    'nav.contact': 'Contact',
    'theme.toggle': 'Toggle theme',
    'language.select': 'Select language',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    
    // Homepage - Animated Slogan
    'hero.animated.tworzymy': 'We create',
    'hero.animated.z': 'with',
    'hero.animated.pasja': 'passion!',
    'hero.title': 'We create with passion!',
    'hero.subtitle': 'We are a company specializing in modern solutions operating in both Web2 and Web3 areas. We test the possibilities of secure data management in a decentralized blockchain environment.',
    'web2.title': 'Web2',
    'web2.description': 'Traditional web applications, content management systems, e-commerce and enterprise solutions',
    'web3.title': 'Web3',
    'web3.description': 'Decentralized applications, blockchain, smart contracts and future technologies',
    'contact.button': 'Contact Us',
    
    // Projects sections
    'projects.web2.title': 'Our Web2 Projects',
    'projects.web2.subtitle': 'Our leading Web2 project is a platform supporting entities organizing collective catering called',
    'projects.web2.subtitle2': 'KaSKa - Capital Catering System',
    'projects.web2.additional': 'The KaSKa system consists of the following three essential elements:',
    'projects.web2.moreInfo': 'More information',
    'projects.web2.project1.title': 'KaSKa Administration',
    'projects.web2.project1.description': 'System administration application with functions:\n- adding and editing nutrition conditions in a specific location,\n- managing user accounts (Parents, Guardians and Children, Fed Persons),\n- generating reports, statements and lists of fed persons\n- and nutrition planning.\nAn integral part of the application is the menu composer module with nutrition planning functions from a ready database of dishes and ingredients.\nThe financial module allows you to control the record of fees for ordered meals and resignation balances.',
    'projects.web2.project2.title': 'KaSKa Parent Panel',
    'projects.web2.project2.description': 'KaSKa Parent Panel is a meal sales platform with payment integration and meal management system. The application works on both computers and mobile devices (tablet, smartphone). It has the following functional features:\n- intuitive creation of Parent and Child/Children accounts with the necessary, minimal amount of personal data entered,\n- meal planning on individual feeding days,\n- possibility to purchase additional meals on days marked as \'no meal\',\n- possibility to resign from a selected meal and cancel this resignation,\n- basket function and resignation balance,\n- active support from IT support teams.\nIt contains an announcements module with current messages from the nutrition organizer.',
    'projects.web2.project3.title': 'KaSKa PikPik',
    'projects.web2.project3.description': 'PikPik is a canteen-kitchen terminal that we install at the serving window in the school canteen. Each Child registered in the system receives a Digital Lunch Card, with which they will be able to \'check in\' at PikPik. PikPik greets the Child, and after checking the card, an invitation to consume the meal selected for that day by the Parent will appear on the screen. At the same time, on the kitchen monitor screen, the staff will have insight into the meal queue, quantities planned, issued and remaining to be issued, as well as diets that should be taken into account on the current day for selected Children. At the end of the day, PikPik will send a report on the course of the nutrition day and automatically turn off. The next day, also automatically, it will turn on at a specified time and independently generate a list of Children fed that day. And all this at no additional cost!',
    
    'projects.web3.title': 'What do we do in Web3?',
    'projects.web3.subtitle': 'We implement pioneering solutions in **blockchain technology** and **decentralized databases**.',
    'projects.web3.intro': 'We have prepared the following Web3 projects:',
    'projects.web3.project1.title': 'DeFi Protocol',
    'projects.web3.project1.description': 'Decentralized finance protocol with staking and yield farming capabilities.',
    'projects.web3.project2.title': 'NFT Marketplace',
    'projects.web3.project2.description': 'NFT trading platform with low transaction fees.',
    'projects.web3.project3.title': 'DAO Governance',
    'projects.web3.project3.description': 'Decentralized autonomous organization management system.',
    
    // Cooperation process
    'cooperation.title': 'Cooperation Process',
    'cooperation.subtitle': 'Four stages of your project implementation',
    'cooperation.stage1.title': '1. Needs Analysis',
    'cooperation.stage1.description': 'Detailed requirements analysis and project scope definition.',
    'cooperation.stage2.title': '2. Design',
    'cooperation.stage2.description': 'Creating system architecture and user interface designs.',
    'cooperation.stage3.title': '3. Implementation',
    'cooperation.stage3.description': 'Application development with regular progress updates.',
    'cooperation.stage4.title': '4. Deployment',
    'cooperation.stage4.description': 'System launch and technical support after deployment.',
    
    // Contact Form
    'contact.title': 'Contact Us',
    'contact.firstName': 'First Name',
    'contact.lastName': 'Last Name',
    'contact.email': 'Email Address',
    'contact.phone': 'Phone Number (optional)',
    'contact.message': 'Message',
    'contact.submit': 'Send Message',
    'contact.cancel': 'Cancel',
    'contact.success': 'Message sent successfully!',
    'contact.error': 'An error occurred while sending the message.',
    'contact.messageLimit': 'Maximum 250 characters',
    'contact.requiredFields': 'All required fields must be filled',
    'contact.sending': 'Sending...',
    'contact.privacyNotice': 'The data entered here will be stored in a decentralized manner (on blockchain). It will not be collected on a traditional server. It will only be visible to the Administrator of this site.',
    
    // Footer
    'footer.copyright': '© 2025. Created by FoxP2 with',
    'footer.copyrightSuffix': 'using',
    'footer.copyrightText': '© 2025. With ❤ by FoxP2',
    'footer.love': '❤️',
    'footer.contact.title': 'Contact',
    'footer.contact.openchat': 'Contact via OpenChat',
    'footer.contact.phone': '+48 503 074 672',
    'footer.contact.email': 'biuro@foxp2.pl',
    'footer.services.title': 'Services',
    'footer.services.web2': 'Web2 Solutions',
    'footer.services.web3': 'Web3 Technologies',
    'footer.services.consulting': 'IT Consulting',
    'footer.principalId.label': 'Your PrincipalID',
    'footer.principalId.admin': 'Administrator account',
    'footer.principalId.copy': 'Copy to clipboard',
    'footer.principalId.copied': 'Copied!',

    // RODO
    'rodo.button': 'GDPR',
    'rodo.title': 'Personal Data Processing Information',
    'rodo.purpose.title': 'Purpose of Data Processing',
    'rodo.purpose.content': 'Personal data provided in the contact form is processed to respond to your inquiry and establish contact regarding FoxP2 company activities.',
    'rodo.scope.title': 'Scope of Processed Data',
    'rodo.scope.firstName': 'First Name',
    'rodo.scope.lastName': 'Last Name',
    'rodo.scope.email': 'Email Address',
    'rodo.scope.phone': 'Phone Number (optional)',
    'rodo.scope.message': 'Message Content',
    'rodo.storage.title': 'Data Storage Method',
    'rodo.storage.content': 'Data is stored in a decentralized manner using Internet Computer blockchain technology. It is not collected on traditional servers, ensuring high security and failure resistance.',
    'rodo.access.title': 'Data Access',
    'rodo.access.content': 'Only the Administrator of the FoxP2 company website has access to the submitted data. Data is not shared with third parties without the consent of the data subject.',
    'rodo.rights.title': 'Rights of Data Subjects',
    'rodo.rights.access': 'Right to access your personal data',
    'rodo.rights.rectification': 'Right to rectify incorrect data',
    'rodo.rights.erasure': 'Right to erasure (right to be forgotten)',
    'rodo.rights.portability': 'Right to data portability',
    'rodo.rights.objection': 'Right to object to processing',
    'rodo.contact.title': 'Contact for Data Protection Matters',
    'rodo.contact.content': 'For matters related to personal data protection, you can contact us at: biuro@foxp2.pl or by phone: +48 503 074 672.',

    // Admin Messages
    'admin.messages.title': 'Messages',
    'admin.messages.dialogTitle': 'Contact Messages',
    'admin.messages.noMessages': 'No contact messages',
    'admin.messages.deleteSuccess': 'Message deleted',
    'admin.messages.deleteError': 'Error deleting message',
    'admin.messages.selectAll': 'Select all',
    'admin.messages.export.button': 'Export to PDF',
    'admin.messages.export.title': 'Contact Messages',
    'admin.messages.export.generated': 'Generated',
    'admin.messages.export.totalMessages': 'Total messages',
    'admin.messages.export.selectedMessages': 'Selected messages',
    'admin.messages.export.name': 'Name',
    'admin.messages.export.email': 'Email',
    'admin.messages.export.phone': 'Phone',
    'admin.messages.export.date': 'Date',
    'admin.messages.export.message': 'Message',
    'admin.messages.export.footer': 'Contact messages generated automatically',
    'admin.messages.export.success': 'PDF generated successfully',
    'admin.messages.export.error': 'Error generating PDF',
    'admin.messages.export.noSelection': 'Select at least one message to export',

    // Scroll to top
    'scrollToTop.label': 'Scroll to top',

    // Web3 Admin
    'web3.admin.title': 'Web3 Card Management',
    'web3.admin.manage': 'Manage',
    'web3.admin.add': 'Add Card',
    'web3.admin.edit': 'Edit Card',
    'web3.admin.description': 'Add or edit cards in the Web3 section',
    'web3.admin.noCards': 'No Web3 cards. Add the first card.',
    'web3.admin.form.title': 'Title',
    'web3.admin.form.titlePlaceholder': 'Enter card title',
    'web3.admin.form.icon': 'Icon',
    'web3.admin.form.description': 'Description',
    'web3.admin.form.descriptionPlaceholder': 'Enter card description',
    'web3.admin.form.buttonTitle': 'Button Text',
    'web3.admin.form.buttonTitlePlaceholder': 'e.g. Learn More',
    'web3.admin.form.link': 'Link',
    'web3.admin.form.linkPlaceholder': 'https://example.com',
    'web3.admin.validation.required': 'All fields are required',
    'web3.admin.success.added': 'Card added successfully',
    'web3.admin.success.updated': 'Card updated successfully',
    'web3.admin.success.deleted': 'Card deleted successfully',
    'web3.admin.error.add': 'Error adding card',
    'web3.admin.error.update': 'Error updating card',
    'web3.admin.error.delete': 'Error deleting card',
    'web3.admin.confirm.delete': 'Are you sure you want to delete this card?',
    'web3.admin.autoTranslation': 'Automatic translation to English and German',
    'web3.admin.form.tab': 'Form',
    'web3.admin.preview.tab': 'Translation Preview',
    'web3.admin.generatePreview': 'Generate Translation Preview',
    'web3.admin.preview.polish': 'Polish (original)',
    'web3.admin.preview.english': 'English (auto)',
    'web3.admin.preview.german': 'Deutsch (auto)',
    'web3.admin.preview.note': 'Translations are generated automatically. The card will be saved in Polish, and translations will be displayed dynamically depending on the selected language.',
    'web3.admin.preview.instruction': 'Fill out the form and click "Generate Translation Preview" to see automatic translations.',

    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
  },
  de: {
    // Header
    'company.name': 'FoxP2',
    'nav.web2': 'Web2',
    'nav.web3': 'Web3',
    'nav.contact': 'Kontakt',
    'theme.toggle': 'Design wechseln',
    'language.select': 'Sprache wählen',
    'auth.login': 'Anmelden',
    'auth.logout': 'Abmelden',
    
    // Homepage - Animated Slogan
    'hero.animated.tworzymy': 'Wir schaffen',
    'hero.animated.z': 'mit',
    'hero.animated.pasja': 'Leidenschaft!',
    'hero.title': 'Wir schaffen mit Leidenschaft!',
    'hero.subtitle': 'Wir sind ein Unternehmen, das sich auf moderne Lösungen spezialisiert hat, die sowohl im Web2- als auch im Web3-Bereich funktionieren. Wir testen die Möglichkeiten der sicheren Datenverwaltung in einer dezentralen Blockchain-Umgebung.',
    'web2.title': 'Web2',
    'web2.description': 'Traditionelle Webanwendungen, Content-Management-Systeme, E-Commerce und Unternehmenslösungen',
    'web3.title': 'Web3',
    'web3.description': 'Dezentrale Anwendungen, Blockchain, Smart Contracts und Zukunftstechnologien',
    'contact.button': 'Kontaktieren Sie uns',
    
    // Projects sections
    'projects.web2.title': 'Unsere Web2-Projekte',
    'projects.web2.subtitle': 'Unser führendes Web2-Projekt ist eine Plattform zur Unterstützung von Einrichtungen, die Gemeinschaftsverpflegung organisieren, genannt',
    'projects.web2.subtitle2': 'KaSKa - Kapitales Catering-System',
    'projects.web2.additional': 'Das KaSKa-System besteht aus den folgenden drei wesentlichen Elementen:',
    'projects.web2.moreInfo': 'Mehr Informationen',
    'projects.web2.project1.title': 'KaSKa Administration',
    'projects.web2.project1.description': 'Systemverwaltungsanwendung mit Funktionen:\n- Hinzufügen und Bearbeiten von Ernährungsbedingungen an einem bestimmten Ort,\n- Verwaltung von Benutzerkonten (Eltern, Betreuer und Kinder, Verpflegte),\n- Generierung von Berichten, Aufstellungen und Listen der Verpflegten\n- sowie Ernährungsplanung.\nEin integraler Bestandteil der Anwendung ist das Menükomponistenmodul mit Ernährungsplanungsfunktionen aus einer fertigen Datenbank von Gerichten und Zutaten.\nDas Finanzmodul ermöglicht die Kontrolle der Aufzeichnung von Gebühren für bestellte Mahlzeiten und Rücktrittsbilanzen.',
    'projects.web2.project2.title': 'KaSKa Elternpanel',
    'projects.web2.project2.description': 'KaSKa Elternpanel ist eine Mahlzeitenverkaufsplattform mit Zahlungsintegration und Mahlzeitenverwaltungssystem. Die Anwendung funktioniert sowohl auf Computern als auch auf mobilen Geräten (Tablet, Smartphone). Sie verfügt über folgende funktionale Merkmale:\n- intuitive Erstellung von Eltern- und Kind-/Kinderkonten mit den erforderlichen, minimalen persönlichen Daten,\n- Mahlzeitenplanung an einzelnen Verpflegungstagen,\n- Möglichkeit, zusätzliche Mahlzeiten an Tagen zu kaufen, die als \'ohne Mahlzeit\' gekennzeichnet sind,\n- Möglichkeit, von einer ausgewählten Mahlzeit zurückzutreten und diesen Rücktritt zu stornieren,\n- Warenkorbfunktion und Rücktrittsbilanz,\n- aktive Unterstützung durch IT-Support-Teams.\nEnthält ein Ankündigungsmodul mit aktuellen Nachrichten vom Verpflegungsorganisator.',
    'projects.web2.project3.title': 'KaSKa PikPik',
    'projects.web2.project3.description': 'PikPik ist ein Kantine-Küchen-Terminal, das wir am Ausgabefenster in der Schulkantine installieren. Jedes im System registrierte Kind erhält eine digitale Mittagskarte, mit der es sich bei PikPik \'einchecken\' kann. PikPik begrüßt das Kind, und nach dem Einchecken der Karte erscheint auf dem Bildschirm eine Einladung, die vom Elternteil für diesen Tag ausgewählte Mahlzeit zu sich zu nehmen. Gleichzeitig hat das Personal auf dem Küchenmonitor Einblick in die Mahlzeitenwarteschlange, geplante, ausgegebene und noch auszugebende Mengen sowie Diäten, die am aktuellen Tag für ausgewählte Kinder berücksichtigt werden sollten. Am Ende des Tages sendet PikPik einen Bericht über den Verlauf des Verpflegungstages und schaltet sich automatisch aus. Am nächsten Tag schaltet es sich ebenfalls automatisch zu einer bestimmten Zeit ein und generiert selbstständig eine Liste der an diesem Tag verpflegten Kinder. Und das alles ohne zusätzliche Kosten!',
    
    'projects.web3.title': 'Was machen wir in Web3?',
    'projects.web3.subtitle': 'Wir implementieren wegweisende Lösungen in **Blockchain-Technologie** und **dezentralen Datenbanken**.',
    'projects.web3.intro': 'Wir haben folgende Web3-Projekte vorbereitet:',
    'projects.web3.project1.title': 'DeFi-Protokoll',
    'projects.web3.project1.description': 'Dezentrales Finanzprotokoll mit Staking- und Yield-Farming-Funktionen.',
    'projects.web3.project2.title': 'NFT-Marktplatz',
    'projects.web3.project2.description': 'NFT-Handelsplattform mit niedrigen Transaktionsgebühren.',
    'projects.web3.project3.title': 'DAO-Governance',
    'projects.web3.project3.description': 'Verwaltungssystem für dezentrale autonome Organisationen.',
    
    // Cooperation process
    'cooperation.title': 'Kooperationsprozess',
    'cooperation.subtitle': 'Vier Phasen der Projektumsetzung',
    'cooperation.stage1.title': '1. Bedarfsanalyse',
    'cooperation.stage1.description': 'Detaillierte Anforderungsanalyse und Projektumfangsdefinition.',
    'cooperation.stage2.title': '2. Design',
    'cooperation.stage2.description': 'Erstellung der Systemarchitektur und Benutzeroberflächendesigns.',
    'cooperation.stage3.title': '3. Implementierung',
    'cooperation.stage3.description': 'Anwendungsentwicklung mit regelmäßigen Fortschrittsaktualisierungen.',
    'cooperation.stage4.title': '4. Bereitstellung',
    'cooperation.stage4.description': 'Systemstart und technischer Support nach der Bereitstellung.',
    
    // Contact Form
    'contact.title': 'Kontaktieren Sie uns',
    'contact.firstName': 'Vorname',
    'contact.lastName': 'Nachname',
    'contact.email': 'E-Mail-Adresse',
    'contact.phone': 'Telefonnummer (optional)',
    'contact.message': 'Nachricht',
    'contact.submit': 'Nachricht senden',
    'contact.cancel': 'Abbrechen',
    'contact.success': 'Nachricht erfolgreich gesendet!',
    'contact.error': 'Beim Senden der Nachricht ist ein Fehler aufgetreten.',
    'contact.messageLimit': 'Maximal 250 Zeichen',
    'contact.requiredFields': 'Alle erforderlichen Felder müssen ausgefüllt werden',
    'contact.sending': 'Wird gesendet...',
    'contact.privacyNotice': 'Die hier eingegebenen Daten werden dezentral (auf der Blockchain) gespeichert. Sie werden nicht auf einem traditionellen Server gesammelt. Sie sind nur für den Administrator dieser Website sichtbar.',
    
    // Footer
    'footer.copyright': '© 2025. Erstellt von FoxP2 mit',
    'footer.copyrightSuffix': 'mit',
    'footer.copyrightText': '© 2025. Mit ❤ von FoxP2',
    'footer.love': '❤️',
    'footer.contact.title': 'Kontakt',
    'footer.contact.openchat': 'Kontakt über OpenChat',
    'footer.contact.phone': '+48 503 074 672',
    'footer.contact.email': 'biuro@foxp2.pl',
    'footer.services.title': 'Dienstleistungen',
    'footer.services.web2': 'Web2-Lösungen',
    'footer.services.web3': 'Web3-Technologien',
    'footer.services.consulting': 'IT-Beratung',
    'footer.principalId.label': 'Ihre PrincipalID',
    'footer.principalId.admin': 'Administratorkonto',
    'footer.principalId.copy': 'In Zwischenablage kopieren',
    'footer.principalId.copied': 'Kopiert!',

    // RODO
    'rodo.button': 'DSGVO',
    'rodo.title': 'Informationen zur Verarbeitung personenbezogener Daten',
    'rodo.purpose.title': 'Zweck der Datenverarbeitung',
    'rodo.purpose.content': 'Die im Kontaktformular angegebenen personenbezogenen Daten werden verarbeitet, um auf Ihre Anfrage zu antworten und Kontakt in Angelegenheiten im Zusammenhang mit den Aktivitäten der Firma FoxP2 aufzunehmen.',
    'rodo.scope.title': 'Umfang der verarbeiteten Daten',
    'rodo.scope.firstName': 'Vorname',
    'rodo.scope.lastName': 'Nachname',
    'rodo.scope.email': 'E-Mail-Adresse',
    'rodo.scope.phone': 'Telefonnummer (optional)',
    'rodo.scope.message': 'Nachrichteninhalt',
    'rodo.storage.title': 'Datenspeicherungsmethode',
    'rodo.storage.content': 'Die Daten werden dezentral mit der Internet Computer Blockchain-Technologie gespeichert. Sie werden nicht auf traditionellen Servern gesammelt, was hohe Sicherheit und Ausfallsicherheit gewährleistet.',
    'rodo.access.title': 'Datenzugriff',
    'rodo.access.content': 'Nur der Administrator der Website der Firma FoxP2 hat Zugriff auf die übermittelten Daten. Die Daten werden nicht ohne Zustimmung der betroffenen Person an Dritte weitergegeben.',
    'rodo.rights.title': 'Rechte der betroffenen Personen',
    'rodo.rights.access': 'Recht auf Zugang zu Ihren personenbezogenen Daten',
    'rodo.rights.rectification': 'Recht auf Berichtigung falscher Daten',
    'rodo.rights.erasure': 'Recht auf Löschung (Recht auf Vergessenwerden)',
    'rodo.rights.portability': 'Recht auf Datenübertragbarkeit',
    'rodo.rights.objection': 'Recht auf Widerspruch gegen die Verarbeitung',
    'rodo.contact.title': 'Kontakt für Datenschutzangelegenheiten',
    'rodo.contact.content': 'Für Angelegenheiten im Zusammenhang mit dem Schutz personenbezogener Daten können Sie uns kontaktieren unter: biuro@foxp2.pl oder telefonisch: +48 503 074 672.',

    // Admin Messages
    'admin.messages.title': 'Nachrichten',
    'admin.messages.dialogTitle': 'Kontaktnachrichten',
    'admin.messages.noMessages': 'Keine Kontaktnachrichten',
    'admin.messages.deleteSuccess': 'Nachricht gelöscht',
    'admin.messages.deleteError': 'Fehler beim Löschen der Nachricht',
    'admin.messages.selectAll': 'Alle auswählen',
    'admin.messages.export.button': 'Als PDF exportieren',
    'admin.messages.export.title': 'Kontaktnachrichten',
    'admin.messages.export.generated': 'Generiert',
    'admin.messages.export.totalMessages': 'Gesamtnachrichten',
    'admin.messages.export.selectedMessages': 'Ausgewählte Nachrichten',
    'admin.messages.export.name': 'Name',
    'admin.messages.export.email': 'E-Mail',
    'admin.messages.export.phone': 'Telefon',
    'admin.messages.export.date': 'Datum',
    'admin.messages.export.message': 'Nachricht',
    'admin.messages.export.footer': 'Kontaktnachrichten automatisch generiert',
    'admin.messages.export.success': 'PDF erfolgreich generiert',
    'admin.messages.export.error': 'Fehler beim Generieren des PDF',
    'admin.messages.export.noSelection': 'Wählen Sie mindestens eine Nachricht zum Exportieren aus',

    // Scroll to top
    'scrollToTop.label': 'Nach oben scrollen',

    // Web3 Admin
    'web3.admin.title': 'Web3-Kartenverwaltung',
    'web3.admin.manage': 'Verwalten',
    'web3.admin.add': 'Karte hinzufügen',
    'web3.admin.edit': 'Karte bearbeiten',
    'web3.admin.description': 'Karten im Web3-Bereich hinzufügen oder bearbeiten',
    'web3.admin.noCards': 'Keine Web3-Karten. Fügen Sie die erste Karte hinzu.',
    'web3.admin.form.title': 'Titel',
    'web3.admin.form.titlePlaceholder': 'Kartentitel eingeben',
    'web3.admin.form.icon': 'Symbol',
    'web3.admin.form.description': 'Beschreibung',
    'web3.admin.form.descriptionPlaceholder': 'Kartenbeschreibung eingeben',
    'web3.admin.form.buttonTitle': 'Button-Text',
    'web3.admin.form.buttonTitlePlaceholder': 'z.B. Mehr erfahren',
    'web3.admin.form.link': 'Link',
    'web3.admin.form.linkPlaceholder': 'https://example.com',
    'web3.admin.validation.required': 'Alle Felder sind erforderlich',
    'web3.admin.success.added': 'Karte erfolgreich hinzugefügt',
    'web3.admin.success.updated': 'Karte erfolgreich aktualisiert',
    'web3.admin.success.deleted': 'Karte erfolgreich gelöscht',
    'web3.admin.error.add': 'Fehler beim Hinzufügen der Karte',
    'web3.admin.error.update': 'Fehler beim Aktualisieren der Karte',
    'web3.admin.error.delete': 'Fehler beim Löschen der Karte',
    'web3.admin.confirm.delete': 'Möchten Sie diese Karte wirklich löschen?',
    'web3.admin.autoTranslation': 'Automatische Übersetzung ins Englische und Deutsche',
    'web3.admin.form.tab': 'Formular',
    'web3.admin.preview.tab': 'Übersetzungsvorschau',
    'web3.admin.generatePreview': 'Übersetzungsvorschau generieren',
    'web3.admin.preview.polish': 'Polnisch (Original)',
    'web3.admin.preview.english': 'English (auto)',
    'web3.admin.preview.german': 'Deutsch (auto)',
    'web3.admin.preview.note': 'Übersetzungen werden automatisch generiert. Die Karte wird auf Polnisch gespeichert, und Übersetzungen werden dynamisch je nach ausgewählter Sprache angezeigt.',
    'web3.admin.preview.instruction': 'Füllen Sie das Formular aus und klicken Sie auf "Übersetzungsvorschau generieren", um automatische Übersetzungen zu sehen.',

    // Common
    'common.loading': 'Wird geladen...',
    'common.save': 'Speichern',
    'common.saving': 'Wird gespeichert...',
    'common.cancel': 'Abbrechen',
    'common.edit': 'Bearbeiten',
    'common.delete': 'Löschen',
    'common.close': 'Schließen',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('pl');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
